package com.hs.basic.entity;

import java.util.Date;

public class BuyHistoryInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buy_history.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buy_history.pur_time
     *
     * @mbg.generated
     */
    private Date purTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buy_history.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buy_history.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buy_history.bstatus
     *
     * @mbg.generated
     */
    private String bstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buy_history.id
     *
     * @return the value of t_buy_history.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buy_history.id
     *
     * @param id the value for t_buy_history.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buy_history.pur_time
     *
     * @return the value of t_buy_history.pur_time
     *
     * @mbg.generated
     */
    public Date getPurTime() {
        return purTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buy_history.pur_time
     *
     * @param purTime the value for t_buy_history.pur_time
     *
     * @mbg.generated
     */
    public void setPurTime(Date purTime) {
        this.purTime = purTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buy_history.cid
     *
     * @return the value of t_buy_history.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buy_history.cid
     *
     * @param cid the value for t_buy_history.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buy_history.uid
     *
     * @return the value of t_buy_history.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buy_history.uid
     *
     * @param uid the value for t_buy_history.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buy_history.bstatus
     *
     * @return the value of t_buy_history.bstatus
     *
     * @mbg.generated
     */
    public String getBstatus() {
        return bstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buy_history.bstatus
     *
     * @param bstatus the value for t_buy_history.bstatus
     *
     * @mbg.generated
     */
    public void setBstatus(String bstatus) {
        this.bstatus = bstatus == null ? null : bstatus.trim();
    }
}