package com.hs.basic.entity;

import java.util.Date;

public class ContentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_content.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_content.ctype
     *
     * @mbg.generated
     */
    private String ctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_content.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_content.clevel
     *
     * @mbg.generated
     */
    private String clevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_content.expire_date
     *
     * @mbg.generated
     */
    private Date expireDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_content.id
     *
     * @return the value of t_content.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_content.id
     *
     * @param id the value for t_content.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_content.ctype
     *
     * @return the value of t_content.ctype
     *
     * @mbg.generated
     */
    public String getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_content.ctype
     *
     * @param ctype the value for t_content.ctype
     *
     * @mbg.generated
     */
    public void setCtype(String ctype) {
        this.ctype = ctype == null ? null : ctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_content.cname
     *
     * @return the value of t_content.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_content.cname
     *
     * @param cname the value for t_content.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_content.clevel
     *
     * @return the value of t_content.clevel
     *
     * @mbg.generated
     */
    public String getClevel() {
        return clevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_content.clevel
     *
     * @param clevel the value for t_content.clevel
     *
     * @mbg.generated
     */
    public void setClevel(String clevel) {
        this.clevel = clevel == null ? null : clevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_content.expire_date
     *
     * @return the value of t_content.expire_date
     *
     * @mbg.generated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_content.expire_date
     *
     * @param expireDate the value for t_content.expire_date
     *
     * @mbg.generated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
}