package com.hs.basic.dao;

import com.hs.basic.entity.BuyHistoryInfo;
import com.hs.basic.entity.BuyHistoryInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyHistoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_history
     *
     * @mbg.generated
     */
    long countByExample(BuyHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_history
     *
     * @mbg.generated
     */
    int deleteByExample(BuyHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_history
     *
     * @mbg.generated
     */
    int insert(BuyHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_history
     *
     * @mbg.generated
     */
    int insertSelective(BuyHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_history
     *
     * @mbg.generated
     */
    List<BuyHistoryInfo> selectByExample(BuyHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BuyHistoryInfo record, @Param("example") BuyHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BuyHistoryInfo record, @Param("example") BuyHistoryInfoExample example);
}