package com.hs.basic.dao;

import com.hs.basic.entity.ContentInfo;

public interface ContentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbg.generated
     */
    int insert(ContentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbg.generated
     */
    int insertSelective(ContentInfo record);
}